<?php
/**
 * Custom B2B SKU display for Product Detail Page
 * @var \Magento\Catalog\Block\Product\View $block
 */
$_product = $block->getProduct();
?>
<?php if ($_product && $_product->getSku()): ?>
    <div class="awa-b2b-pdp-sku">
        <span class="awa-b2b-sku__label">Cod:</span>
        <span class="awa-b2b-sku__value"><?php echo $block->escapeHtml($_product->getSku()); ?></span>
    </div>
<?php endif; ?>
