<?php
/**
 * Widget de acessibilidade VLibras (gov.br)
 * https://vlibras.gov.br/doc/widget/installation/
 *
 * @var \GrupoAwamotos\Vlibras\Block\Vlibras $block
 */
?>
<?php if ($block->isEnabled()): ?>
<div vw class="enabled" aria-hidden="true">
    <div vw-access-button class="active"></div>
    <div vw-plugin-wrapper>
        <div class="vw-plugin-top-wrapper"></div>
    </div>
</div>
<script src="https://vlibras.gov.br/app/vlibras-plugin.js"></script>
<script>
    new window.VLibras.Widget('https://vlibras.gov.br/app');
</script>
<?php endif; ?>
