<?php
/** @var \GrupoAwamotos\B2B\CommercialPanel\Block\Adminhtml\Goal\Toolbar $block */
?>
<?php if ($block->canManageGoals()): ?>
<div class="page-main-actions">
    <div class="page-actions">
        <div class="page-actions-buttons">
            <a class="action-primary" href="<?= $block->escapeUrl($block->getEditUrl()) ?>">
                <?= $block->escapeHtml(__('Cadastrar Meta')) ?>
            </a>
        </div>
    </div>
</div>
<?php endif; ?>
