<?php
declare(strict_types=1);
$cssUrl = $this->getViewFileUrl('css/awa-visual-audit-final-2026-05-03.css');
$overhaulCssUrl = $this->getViewFileUrl('css/awa-visual-overhaul-2026-05-04.css');
$improvementsCssUrl = $this->getViewFileUrl('css/awa-visual-improvements-2026-05-05.css');
?>
<link rel="stylesheet" href="<?= $this->escapeUrl($cssUrl) ?>?v=10" media="all"/>
<link rel="stylesheet" href="<?= $this->escapeUrl($overhaulCssUrl) ?>?v=4" media="all"/>
<link rel="stylesheet" href="<?= $this->escapeUrl($improvementsCssUrl) ?>?v=4" media="all"/>
