<?php
declare(strict_types=1);

return [
    'source_groups' => [
        'application' => [
            'var/log/system.log',
            'var/log/system.log.*',
            'var/log/exception.log',
            'var/log/exception.log.*',
            'var/log/debug.log',
            'var/log/debug.log.*',
            'var/log/magento.cron.log',
            'var/log/magento.cron.log.*',
            'var/log/magento.cron.default.log',
            'var/log/magento.cron.default.log.*',
            'var/log/magento.cron.index.log',
            'var/log/magento.cron.index.log.*',
        ],
        'erp' => [
            'var/log/erp_integration.log',
            'var/log/erp_integration.log.*',
            'var/log/erp-order-sync.log',
            'var/log/erp-order-sync.log.*',
            'var/log/erp-order-sync-error.log',
            'var/log/erp-order-sync-error.log.*',
            'var/log/erp-order-sync-retry.log',
            'var/log/erp-order-sync-retry.log.*',
            'var/log/erp-order-sync-retry-error.log',
            'var/log/erp-order-sync-retry-error.log.*',
            'var/log/erp-consumer.log',
            'var/log/erp-consumer.log.*',
        ],
        'database' => [
            'var/log/mysql_error.log',
            'var/log/mysql_error.log.*',
            'var/log/redis.log',
            'var/log/redis.log.*',
            '/var/log/mysql/error.log',
            '/var/log/mysql/error.log.*',
        ],
        'third_party' => [
            'var/log/commerce-data-export-errors.log',
            'var/log/commerce-data-export-errors.log.*',
            'var/log/commerce-data-export.log',
            'var/log/commerce-data-export.log.*',
            'var/log/meta_fbe.log',
            'var/log/meta_fbe.log.*',
            'var/log/marketing_intelligence.log',
            'var/log/marketing_intelligence.log.*',
        ],
        'server' => [
            '/var/log/nginx/error.log',
            '/var/log/nginx/error.log.*',
            '/var/log/nginx/access.log',
            '/var/log/nginx/access.log.*',
        ],
    ],
    'default_groups' => [
        'application',
        'erp',
        'database',
        'third_party',
        'server',
    ],
    'severity_order' => [
        'DEBUG' => 10,
        'INFO' => 20,
        'NOTICE' => 30,
        'WARNING' => 40,
        'ERROR' => 50,
        'CRITICAL' => 60,
        'ALERT' => 70,
        'EMERGENCY' => 80,
    ],
    'alerts' => [
        [
            'name' => 'critical-events',
            'metric' => 'level',
            'level' => 'CRITICAL',
            'window_days' => 2,
            'warning_threshold' => 1,
            'critical_threshold' => 5,
        ],
        [
            'name' => 'error-events',
            'metric' => 'level',
            'level' => 'ERROR',
            'window_days' => 2,
            'warning_threshold' => 10,
            'critical_threshold' => 25,
        ],
        [
            'name' => 'fitment-autocomplete-typeerror',
            'metric' => 'pattern',
            'match' => 'SearchAutocompleteProductPlugin::afterMap',
            'window_days' => 2,
            'warning_threshold' => 1,
            'critical_threshold' => 3,
        ],
        [
            'name' => 'queue-consumers-namespace',
            'metric' => 'pattern',
            'match' => 'There are no commands defined in the "queue:consumers" namespace.',
            'window_days' => 7,
            'warning_threshold' => 1,
            'critical_threshold' => 3,
        ],
        [
            'name' => 'erp-stock-anomalies',
            'metric' => 'pattern',
            'match' => 'Stock anomalies detected during sync',
            'window_days' => 2,
            'warning_threshold' => 1,
            'critical_threshold' => 5,
        ],
        [
            'name' => 'cron-runtime',
            'metric' => 'cron_max_seconds',
            'warning_threshold' => 60.0,
            'critical_threshold' => 180.0,
        ],
        [
            'name' => 'unreadable-source',
            'metric' => 'unreadable_sources',
            'warning_threshold' => 1,
            'critical_threshold' => 2,
        ],
        [
            'name' => 'queue-strategy-drift',
            'metric' => 'config_drift',
            'warning_threshold' => 1,
            'critical_threshold' => 1,
        ],
    ],
];
